name: CI Pipeline
on: [push, pull_request]  # Trigger on all branches for testing

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Debug: Print environment info
      - name: Debug - Show Context
        run: |
          echo "Branch: ${{ github.ref }}"
          echo "Event: ${{ github.event_name }}"
          pwd
          ls -la

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # Node Setup
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Python Setup
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      # Python dependencies
      - name: Install Python packages
        run: pip install -r requirements.txt flake8 nose

      # Linting
      - name: Run Flake8 linting
        run: flake8 . --count --show-source --statistics

      # Testing
      - name: Run Nose tests
        run: nosetests -v

      # Build
      - name: Build project
        run: npm run build