name: CI Pipeline
on: [push, pull_request]  # Triggers on all pushes and PRs

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Prevent hanging jobs
    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full commit history for better analysis

      # 2. Setup Python environment
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Specify your Python version
          cache: 'pip'  # Cache pip dependencies for faster runs

      # 3. Install Python dependencies
      - name: Install Python packages
        run: |
          pip install --upgrade pip  # Ensure pip is current
          pip install flake8 nose  # Required tools
          if [ -f requirements.txt ]; then  # Install project deps if exists
            pip install -r requirements.txt
          fi

      # 4. Run Flake8 linting
      - name: Lint with Flake8
        run: flake8 . --count --show-source --statistics

      # 5. Run tests with nose
      - name: Run tests with nose
        run: nosetests -v --with-coverage  # Verbose mode with coverage

      # 6. Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Specify your Node version
          cache: 'npm'  # Cache npm dependencies

      # 7. Install Node dependencies
      - name: Install Node packages
        if: contains(github.event.head_commit.message, 'package.json') || true
        run: npm ci  # Clean install for reproducibility

      # 8. Build project
      - name: Build project
        run: npm run build --if-present  # Run only if build script exists