name: CI Pipeline  # 1. Create GitHub workflow

# 2. Add events to trigger the workflow
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

# 3. Add a job to the workflow
jobs:
  build-and-test:  # Job ID
    name: Build and Test
    # 4. Add job runner (GitHub-hosted Ubuntu)
    runs-on: ubuntu-latest
    
    # 5. Add container to job runner
    container:
      image: node:20-alpine  # Official Node.js container
      options: --user node --workdir /home/node/app
      volumes:
        - /home/node/app/node_modules  # Cache node_modules

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run tests
      - name: Execute tests
        run: npm test

      # Build project
      - name: Build project
        run: npm run build