name: CI workflow  # 1. Create GitHub workflow

# 2. Add events to trigger the workflow
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

# 3. Add a job to the workflow
jobs:
  build-and-test:  # Job ID
    name: Build and Test
    # 4. Add job runner (GitHub-hosted Ubuntu)
    runs-on: ubuntu-latest
    
    # 5. Add container to job runner
    container:
      image: node:20-alpine  # Official Node.js container
      options: --user node --workdir /home/node/app
      volumes:
        - /home/node/app/node_modules  # Cache node_modules

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install dependencies
      - name: Install Node dependencies
        run: npm ci
      # python environment setup
      - name: Setup python
        uses: action/setup-python@v5
        with: 
          python-version: '3.11'

      - name: Install python dependencies
        run: pip Install -r requirements.txt

      # Lint code with Flake8
      - name: Lint with Flake8
        run: |
          pip Install Flake8
          flake8 . --count --show-source --statistics
      # Run unit tests with nose 
      - name: Run Python tests with nose 
        run: |
          pip Install nose
          nosetests -v 
          
      # Run tests
      - name: Execute tests
        run: npm test

      # Build project
      - name: Build project
        run: npm run build